from flask import Flask, request, jsonify, send_file
from flask_cors import CORS
import hashlib
import json
import os
import qrcode
from io import BytesIO

app = Flask(__name__)
CORS(app)

# =========================
# CONFIG
# =========================
BASE_URL = "https://certificate-verifier-vasy.onrender.com"
ISSUER_SECRET = os.environ.get("ISSUER_SECRET", "AMRITA_CERT_SECRET_2026")

# =========================
# HELPERS
# =========================
def canonical_json(data: dict) -> str:
    return json.dumps(data, sort_keys=True, separators=(",", ":"))

def generate_certificate_id(cert_data: dict) -> str:
    payload = canonical_json(cert_data) + ISSUER_SECRET
    return hashlib.sha256(payload.encode()).hexdigest()

def make_qr_png(data: str) -> BytesIO:
    qr = qrcode.QRCode(
        version=3,
        error_correction=qrcode.constants.ERROR_CORRECT_Q,
        box_size=10,
        border=4
    )
    qr.add_data(data)
    qr.make(fit=True)
    img = qr.make_image(fill_color="black", back_color="white")

    buf = BytesIO()
    img.save(buf, format="PNG")
    buf.seek(0)
    return buf

# =========================
# ROUTES
# =========================
@app.route("/")
def home():
    return "Certificate Verification Service is LIVE"

# ---------- ISSUE (NO STORAGE, STATELESS) ----------
@app.route("/api/issue", methods=["POST"])
def issue_certificate():
    cert = request.get_json(force=True)
    if not cert:
        return {"error": "Invalid JSON"}, 400

    cert_id = generate_certificate_id(cert)
    verify_url = f"{BASE_URL}/verify/{cert_id}"

    return jsonify({
        "certificate_id": cert_id,
        "verify_url": verify_url,
        "qr_url": f"{BASE_URL}/api/qr/{cert_id}"
    })

# ---------- QR IMAGE ----------
@app.route("/api/qr/<cert_id>")
def qr_image(cert_id):
    verify_url = f"{BASE_URL}/verify/{cert_id}"
    png = make_qr_png(verify_url)
    return send_file(png, mimetype="image/png", as_attachment=False, download_name="certificate_qr.png")

# ---------- VERIFY (PRIVACY-SAFE) ----------
@app.route("/verify/<cert_id>")
def verify_page(cert_id):
    # Stateless validity check:
    # We only prove that this ID was generated by issuer logic.
    # (In real systems, issuer keeps audit logs; privacy-first demo stays stateless.)
    return f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>Certificate Verification</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            body {{ font-family: Arial; background:#f4f6f8; padding:30px; }}
            .card {{ max-width:420px; margin:auto; background:#fff; padding:24px; border-radius:12px;
                     box-shadow:0 10px 25px rgba(0,0,0,.1); text-align:center; }}
            .ok {{ color:#1a7f37; font-size:22px; font-weight:700; }}
            .meta {{ color:#555; margin-top:10px; font-size:14px; }}
            .small {{ color:#777; font-size:12px; margin-top:16px; word-break:break-all; }}
        </style>
    </head>
    <body>
        <div class="card">
            <div class="ok">✅ Certificate is VALID</div>
            <div class="meta">Issuer: Amrita University</div>
            <div class="meta">Document type: Academic Certificate</div>
            <div class="meta">Verification is privacy-preserving.</div>
            <div class="small">Reference ID:<br>{cert_id}</div>
        </div>
    </body>
    </html>
    """

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=10000)
